### ISSUE TITLE
Understand block comments in assembly (`.s`) files

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/dotnes#14]
Examples like:

https://8bitworkshop.com/v3.10.0/?platform=nes&file=chr_generic.s

Have lines like this:
```assembly
;;{w:8,h:8,bpp:1,count:256,brev:1,np:2,pofs:8,remap:[0,1,2,4,5,6,7,8,9,10,11,12]};;
...
;/* use block comment to map a subset of data to sprite bitmaps */
;/*{w:16,h:16,bpp:1,count:15,brev:1,np:2,pofs:8,remap:[5,0,1,2,4,6,7,8,9,10,11,12]}*/
```

I just removed them from samples / tests. Because they don't appear to affect the binary output.

We should understand what these are, and if we need them.

**Comment by charlesbetros** [comment]
These seem to be used to the pixel editor in the 8 bit workshop ide. They appear in assets for multiple machine types. If you modify the values in the comment it causes the image to be rendered differently.

https://github.com/sehugg/8bitworkshop/blob/d733a2cd273cf6e0d33c2f780e1e17e1da0c17e9/src/ide/pixeleditor.ts#L29

**Comment by jonathanpeppers** [comment]
So sounds like these numbers don't affect the binary output, thanks!
