### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amir16yp** [jonathanpeppers/dotnes#28]
Hey, I really like what you did with this project here. I was trying to port some examples that use neslib from [this repo](https://github.com/jmk/cc65-nes-examples), specifically [example2](https://github.com/jmk/cc65-nes-examples/blob/master/example2.c). I saw that some functions aren't really implemented, specifically `pal_spr` which is why i cant compile it.

In this [this line](https://github.com/jonathanpeppers/dotnes/blob/38cb5e22bf1b38507944c0ee85eda66fc3b73ebb/src/dotnes.tasks/Utilities/IL2NESWriter.cs#L319) you define addresses for the functions, only a few are really implemented. I'm no assembly wizard, but can i ask what are those addresses and would it hard to just find the rest of them and get them implemented? Thanks in advance.

**Comment by jonathanpeppers** [comment]
If you go to 8bitworkshop.com, and just load hello.c for the NES, the disassembly has the addresses. There is also another spot to put the number of arguments.

I would share screenshots, etc. but I’m on vacation this week with no computer. 😀

I’m also open if someone comes up with a better idea, too. 👍

**Comment by amir16yp** [comment]
im working on adding the rest of the addresses + the num of arguments for each one. will send a pull request soon, but not all of them would work immediately, some of them that i tested get an opcode error, so i assume that would require further work.
