### ISSUE TITLE
[Suggestion] New Logo?

### ISSUE THREAD

**Issue by IamFastre** [jonathanpeppers/dotnes#31]
<div align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/2080671f-4050-423a-8b59-58cb9c96c43e" />
</div>
<p align="center">
    <a href="https://github.com/user-attachments/files/15527477/dotnes.zip">
        dotnes.zip
    </a>
</p>
<br/>

I designed this logo that combines both the [NES](https://upload.wikimedia.org/wikipedia/commons/0/0d/NES_logo.svg) and the [.NET](https://upload.wikimedia.org/wikipedia/commons/7/7d/Microsoft_.NET_logo.svg) logos, while still retaining the pixel art side of the current one.
It's no big thing, actually maybe worse, but I really am not admiring that AI-generated one.

**Comment by jonathanpeppers** [comment]
@IamFastre are you fine for me to make these couple changes and use this logo? I will put your name in the appropriate spots as the logo designer.

Or if you are able update the `.zip` or have other ideas, that works, too. Thanks!

**Comment by IamFastre** [comment]
Hey @jonathanpeppers! Sorry for the late reply; exams are quite overwhelming, anyway, I wanted to include .NET somehow. But the logo doesn't have that much of characteristics, so it's currently looking like:

<div align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/a8b16159-f5d8-4376-a02e-0b080b21f169" width=250/>
</div>

but I thought a little Microsoft-y touch would be nice, not sure of the legality of it though.

<div align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/6d51ca67-74c6-4521-9a4b-50d55bd84c06" width="250" />
</div>

I also made non-pixel art versions:

<div align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/7afdf3d2-265e-4377-828c-548fd1cc1c71" width="250" />
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/507b1227-4cdb-4065-82b1-84695edeae5e" width="250"/>
</div>

And finally transparent ones:

<div align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/84aa8ae2-1dc7-4254-bd97-a66e605fa3aa" width="250" />
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/ca4b8580-ec5d-40f8-a5b7-e5517f8953d5" width="250"/>
</div>

<p align="center">
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/f4ed2165-9a2f-439d-bcfa-6ff322bc6acd" width="250" />
    <img src="https://github.com/jonathanpeppers/dotnes/assets/61952761/db1ac07d-ec66-4b45-8e86-8c64e5612dbe" width="250"/>
</p>

The [dotnes.zip](https://github.com/user-attachments/files/15751008/dotnes.zip) contains all of these exports _(in addition to the SVGs and the `10x` for the pixel art ones)_ with the **Illustrator** and **Aseprite** files as well!
Use them all as you like and if you have any other suggestions I can be of help!

**Comment by jonathanpeppers** [comment]
I'm not worried about the 🪟-looking part, but I work for them!

I merged in changes using your logo, you show up as a contributor now, thanks!

![image](https://github.com/jonathanpeppers/dotnes/assets/840039/0299228f-1be9-4a42-b3ce-ade22008fd79)

**Comment by IamFastre** [comment]
We can switch it up for the 4 colors of the NES controller: black, gray, white, and red.
But really looks great on the readme!
