### ISSUE TITLE
Test Console

### ISSUE THREAD

**Issue by charlesbetros** [jonathanpeppers/dotnes#41]
### Discussed in https://github.com/jonathanpeppers/dotnes/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **charlesbetros** August 23, 2024</sup>
I think a console app that runs the transpile task might be useful. I wrote a really simple one for my local dev. We could do some assembly output comparisons for basic acceptance tests. I haven't put much thought in to selecting a project to "run".</div>

**Comment by jonathanpeppers** [comment]
FYI I took this even further with:
* #45 

```
> dotnet tool install -g dotnes.compiler --add-source .\bin\Debug\ --prerelease
You can invoke the tool using the following command: dotnes
Tool 'dotnes.compiler' (version '0.1.1-alpha') was successfully installed.
```

Then you can just run it via:

```
> dotnes
Usage: dotnes.exe mydll.dll chr_generic.s
```
